### PR TITLE
Add manifests to deploy a Standalone Argo Server in Openshift

### PR DESCRIPTION
**Pull request by gmfrasca**
Add manifests to deploy a Standalone Argo Server in Openshift

## Description
Add manifests to deploy a Standalone Argo Server in Openshift

## How Has This Been Tested?
```
cd manifests/deploy-argo-server
oc apply -k -n <namespace> openshift
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by gregsheremeta** [comment]
this is awesome! Thanks so much for doing this.

...

couldn't verify. argo-server crashes with:

```
time="2024-09-05T00:53:45.684Z" level=info msg="not enabling pprof debug endpoints"
time="2024-09-05T00:53:45.685Z" level=info authModes="[server]" baseHRef=/ managedNamespace=dspa1 namespace=dspa1 secure=true ssoNamespace=dspa1
time="2024-09-05T00:53:45.685Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
time="2024-09-05T00:53:45.686Z" level=warning msg="You are running without client authentication. Learn how to enable client authentication: https://argo-workflows.readthedocs.io/en/release-3.4/argo-server-auth-mode/"
time="2024-09-05T00:53:45.686Z" level=info msg="SSO disabled"
time="2024-09-05T00:53:45.704Z" level=fatal msg="configmaps \"workflow-controller-configmap\" not found"
```

In my DSP project, the workflow controller configmap is named `ds-pipeline-workflow-controller-dspa1`. If I copy that into a configmap named `workflow-controller-configmap`, and I remove the `containerRuntimeExecutor` key, it works.

**Comment by gmfrasca** [comment]
@gregsheremeta - ah, good catch: the default `workflow-controller-configmap` had already existed in my test namespace so didn't catch it.   As it turns out you just need a CM with that specific name - Argo Server doesn't appear to care about whats actually in the contents - so I just added an empty one to the manifests such that deployment will work.

we can expand the capabilities of the deployment and point to an actual DSP WC ConfigMap later if we deem it necessary, but for now this should be fine

**Comment by gregsheremeta** [comment]
/lgtm

thanks!

**Pull request merged**
